import {
  LaptopOutlined,
  NotificationOutlined,
  UserOutlined,
} from "@ant-design/icons";
import { DownOutlined } from "@ant-design/icons";
import { MenuProps, Space } from "antd";
import { Layout as AntdLayout, Breadcrumb, Dropdown, Menu,theme } from "antd";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React, { ReactNode } from "react";

import styles from "./index.module.css";

const { Header, Content, Sider } = AntdLayout;

const items1: MenuProps["items"] = ["1", "2", "3"].map((key) => ({
  key,
  label: `nav ${key}`,
}));

const items2: MenuProps["items"] = [
  UserOutlined,
  LaptopOutlined,
  NotificationOutlined,
].map((icon, index) => {
  const key = String(index + 1);

  return {
    key: `sub${key}`,
    icon: React.createElement(icon),
    label: `subnav ${key}`,

    children: new Array(4).fill(null).map((_, j) => {
      const subKey = index * 4 + j + 1;
      return {
        key: subKey,
        label: `option${subKey}`,
      };
    }),
  };
});

const ITEMS = [
  {
    // icon: React.createElement(icon),
    label: "Book Management",
    key: "book",

    children: [
      { label: "Book List", key: "/book" },
      { label: "Add Book", key: "/book/add" },
    ],
  },
  {
    // icon: React.createElement(icon),
    label: "Borrow Management",
    key: "borrow",

    children: [
      { label: "Borrow List", key: "/borrow" },
      { label: "Borrow Book", key: "/borrow/add" },
    ],
  },
  {
    // icon: React.createElement(icon),
    label: "Category Management",
    key: "category",

    children: [
      { label: "Category List", key: "/category" },
      { label: "Add Category", key: "/category/add" },
    ],
  },
  {
    // icon: React.createElement(icon),
    label: "User Management",
    key: "user",

    children: [
      { label: "User List", key: "/user" },
      { label: "Add User", key: "/user/add" },
    ],
  },
];

const USER_ITEMS: MenuProps["items"] = [
  {
    label: "User Center",
    key: "1",
  },
  {
    label: "Log Out",
    key: "2",
  },
];

export function Layout({ children }:{children:ReactNode}) {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();

  const router = useRouter();
  const handleMenuClick: MenuProps['onClick'] = ({ key }) => {
    router.push(key);
    console.log(key)
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AntdLayout>
          <Header className={styles.header}>
            <Image
              src="/book.png"
              width={30}
              height={30}
              alt="logo"
              className={styles.logo}
            />
            Library System
            <span className={styles.user}>
              <Dropdown menu={{ items: USER_ITEMS }}>
                <a onClick={(e) => e.preventDefault()}>
                  <Space>
                    User Name
                    <DownOutlined />
                  </Space>
                </a>
              </Dropdown>
            </span>
          </Header>
          <AntdLayout className={styles.sectionInner}>
            <Sider width={250} >
              <Menu
                mode="inline"
                defaultSelectedKeys={["/book"]}
                defaultOpenKeys={["book"]}
                style={{ height: "100%", borderRight: 0 }}
                items={ITEMS}
                onClick={handleMenuClick}
                className={styles.menu}
              />
            </Sider>
            <AntdLayout className={styles.sectionContent}>
              <Content className={styles.content}>{children}</Content>
            </AntdLayout>
          </AntdLayout>
        </AntdLayout>
      </main>
    </>
  );
}
